const NODE_ENV = process.env.NODE_ENV!;

const DATA_BASE_URL = process.env.DATA_BASE_URL!;
const AUTH_SECRET = process.env.AUTH_SECRET!;

const GITHUB_ID = process.env.GITHUB_ID!;
const GITHUB_SECRET = process.env.GITHUB_SECRET!;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;

const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
const NODEMAILER_MAIL_HOST = process.env.NODEMAILER_MAIL_HOST!;
const NODEMAILER_MAIL_SERVICE_PROVIDER =
  process.env.NODEMAILER_MAIL_SERVICE_PROVIDER!;
const NODEMAILER_EMAIL_SERVER_USER = process.env.NODEMAILER_EMAIL_SERVER_USER!;
const NODEMAILER_GMAIL_PASS_KEY = process.env.NODEMAILER_GMAIL_PASS_KEY!;
const NODEMAILER_EMAIL_SENDER = process.env.NODEMAILER_EMAIL_SENDER!;
const NODEMAILER_ADMIN_EMAIL = process.env.NODEMAILER_ADMIN_EMAIL!;

const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET!;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET!;
const LOCAL_DATABASE_URL = process.env.LOCAL_DATABASE_URL!;

const SECRETS_PASSWORD = process.env.SECRETS_PASSWORD!;
const CLIENT_URL = process.env.CLIENT_URL!;

const UPLOADTHING_TOKEN = process.env.UPLOADTHING_TOKEN!;
const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID!;
const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET!;

export {
  NODE_ENV,
  DATA_BASE_URL,
  AUTH_SECRET,
  GITHUB_ID,
  GITHUB_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  NODEMAILER_EMAIL_SENDER,
  NODEMAILER_MAIL_HOST,
  NODEMAILER_GMAIL_PASS_KEY,
  NODEMAILER_EMAIL_SERVER_USER,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  NODEMAILER_MAIL_SERVICE_PROVIDER,
  LOCAL_DATABASE_URL,
  NODEMAILER_ADMIN_EMAIL,
  SECRETS_PASSWORD,
  CLIENT_URL,
  UPLOADTHING_TOKEN,
  GITHUB_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
};
