const NODE_ENV = process.env.NODE_ENV!;
const DATA_BASE_URL = process.env.DATA_BASE_URL!;
const AUTH_SECRET = process.env.AUTH_SECRET!;
const GITHUB_ID = process.env.GITHUB_ID!;
const GITHUB_SECRET = process.env.GITHUB_SECRET!;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
const EMAIL_SERVER_HOST = process.env.EMAIL_SERVER_HOST!;
const EMAIL_SERVER_PORT = process.env.EMAIL_SERVER_PORT!;
const EMAIL_SERVER_USER = process.env.EMAIL_SERVER_USER!;
const EMAIL_SERVER_PASSWORD = process.env.EMAIL_SERVER_PASSWORD!;
const EMAIL_FROM = process.env.EMAIL_FROM!;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET!;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET!;

export {
  NODE_ENV,
  DATA_BASE_URL,
  AUTH_SECRET,
  GITHUB_ID,
  GITHUB_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  EMAIL_FROM,
  EMAIL_SERVER_HOST,
  EMAIL_SERVER_PASSWORD,
  EMAIL_SERVER_PORT,
  EMAIL_SERVER_USER,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
};
